# Generated by Django 4.0.1 on 2022-01-13 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ename', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=150)),
                ('num', models.CharField(max_length=150)),
                ('gender', models.CharField(choices=[('m', 'male'), ('f', 'female')], default=False, max_length=1)),
                ('address', models.CharField(max_length=150)),
                ('comment', models.TextField(max_length=150)),
            ],
        ),
    ]
