# Generated by Django 4.0.1 on 2022-01-16 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_form_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='gender',
            field=models.CharField(choices=[('Male', 'male'), ('Female', 'female')], default=False, max_length=6),
        ),
    ]
