# Generated by Django 4.0.1 on 2022-01-16 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_form_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='address',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='form',
            name='comment',
            field=models.TextField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='form',
            name='num',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
