# Generated by Django 4.0.1 on 2022-01-16 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_form_address_alter_form_comment_alter_form_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='email',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='form',
            name='ename',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
