# Generated by Django 4.0.1 on 2022-01-17 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_form_email_alter_form_ename'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='plans',
            field=models.CharField(max_length=9, null=True),
        ),
    ]
